export const pastWinners2024 = {
  year: 2024,
  orderedWinners: [
    {
      place: '1st Place',
      teamName: 'Git Kermit',
      image: '/winners/2024/2024-1st.jpg',
      members: [
        'Cory Brown',
        'Kevin Cao',
        'Shuhei Yokkaichi',
        'Samuel Chung',
        'Jessica Zeng',
        'Chris Oliver',
      ],
      contacts: [
        'Cbro223@aucklanduni.ac.nz',
        'kcao657@aucklanduni.ac.nz',
        'Syok443@aucklanduni.ac.nz',
        'schu718@aucklanduni.ac.nz',
        'Szen566@aucklanduni.ac.nz',
        'Coli772@aucklanduni.ac.nz',
      ],
    },
    {
      place: '2nd Place',
      teamName: 'Java Skunk',
      image: '/winners/2024/2024-2nd.jpg',
      members: [
        'Jason Huang',
        'Chris Valenzuela',
        'Kinzi Ceolin',
        'Siyeon Kim',
        'Xin Yue',
        'Skyler Solomon-Gavin',
      ],
      contacts: [
        'jhua540@aucklanduni.ac.nz',
        'cval893@aucklanduni.ac.nz',
        'kceo161@aucklanduni.ac.nz',
        'skim411@aucklanduni.ac.nz',
        'xyue918@aucklanduni.ac.nz',
        'ssol696@aucklanduni.ac.nz',
      ],
    },
    {
      place: '3rd Place',
      teamName: 'Kappachungus',
      image: '/winners/2024/2024-3rd.jpg',
      members: [
        'Ryan Yoon',
        'Joshua Morley',
        'Ray Xiao',
        'Katie Zhou',
        'Connor Williams',
        'Jaap Skinner',
      ],
      contacts: [
        'ryoo514@aucklanduni.ac.nz',
        'jmor490@aucklanduni.ac.nz',
        'rxia357@aucklanduni.ac.nz',
        'kzho904@aucklanduni.ac.nz',
        'cwil915@aucklanduni.ac.nz',
        'jski306@aucklanduni.ac.nz',
      ],
    },
  ],
  specialAwards: [
    {
      place: 'Most Overengineered',
      teamName: 'Exception Handlers',
      image: '/winners/2024/2024-4th.jpg',
      members: [
        'Aref Osman',
        'Alex Brown',
        'Brandon Seng Han Chan',
        'Daniel Munn',
        'Henry Ly',
        'James Tasker',
      ],
      contacts: [
        'aosm976@aucklanduni.ac.nz',
        'abro522@aucklanduni.ac.nz',
        'bcha389@aucklanduni.ac.nz',
        'dmun793@aucklanduni.ac.nz',
        'hly852@aucklanduni.ac.nz',
        'jtas575@aucklanduni.ac.nz',
      ],
    },
    {
      place: 'Best Design',
      teamName: 'Git Kermit',
      image: '/winners/2024/2024-5th.jpg',
      members: [
        'Cory Brown',
        'Kevin Cao',
        'Shuhei Yokkaichi',
        'Samuel Chung',
        'Jessica Zeng',
        'Chris Oliver',
      ],
      contacts: [
        'Cbro223@aucklanduni.ac.nz',
        'kcao657@aucklanduni.ac.nz',
        'Syok443@aucklanduni.ac.nz',
        'schu718@aucklanduni.ac.nz',
        'Szen566@aucklanduni.ac.nz',
        'Coli772@aucklanduni.ac.nz',
      ],
    },
    {
      place: 'Most Entertaining',
      teamName: 'print(“hello world”)',
      image: '/winners/2024/2024-6th.jpg',
      members: [
        'Andre Camerino',
        'Evan Au',
        'Luase Fontaine',
        'Ashlee Shum',
        'Gabrielle Esguerra',
        'Jayden Newport',
      ],
      contacts: [
        'rcam301@aucklanduni.ac.nz',
        'eau465@aucklanduni.ac.nz',
        'lfon434@aucklanduni.ac.nz',
        'ashlee@shum.co.nz',
        'esguerra.gabrielle12@gmail.com',
        'jtnew.king@gmail.com',
      ],
    },
  ],
};
