export const pastWinners2024 = {
  year: 2024,
  orderedWinners: [
    {
      place: '1st Place',
      teamName: 'Git Kermit',
      image: '/winners/2024/2024-1st copy.jpg',
      members: [
        'Cory Brown',
        'Kevin Cao',
        'Shuhei Yokkaichi',
        'Samuel Chung',
        'Jessica Zeng',
        'Chris Oliver',
      ],
    },
    {
      place: '2nd Place',
      teamName: 'Java Skunk',
      image: '/winners/2024/2024-2nd copy.jpg',
      members: [
        'Jason Huang',
        'Chris Valenzuela',
        'Kinzi Ceolin',
        'Siyeon Kim',
        'Xin Yue',
        'Skyler Solomon-Gavin',
      ],
    },
    {
      place: '3rd Place',
      teamName: 'Kappachungus',
      image: '/winners/2024/2024-3rd copy.jpg',
      members: [
        'Ryan Yoon',
        'Joshua Morley',
        'Ray Xiao',
        'Katie Zhou',
        'Connor Williams',
        'Jaap Skinner',
      ],
    },
  ],
  specialAwards: [
    {
      place: 'Most Overengineered',
      teamName: 'Exception Handlers',
      image: '/winners/2024/2024-4th copy.jpg',
      members: [
        'Aref Osman',
        'Alex Brown',
        'Brandon Seng Han Chan',
        'Daniel Munn',
        'Henry Ly',
        'James Tasker',
      ],
    },
    {
      place: 'Best Design',
      teamName: 'Git Kermit',
      image: '/winners/2024/2024-5th copy.jpg',
      members: [
        'Cory Brown',
        'Kevin Cao',
        'Shuhei Yokkaichi',
        'Samuel Chung',
        'Jessica Zeng',
        'Chris Oliver',
      ],
    },
    {
      place: 'Most Entertaining',
      teamName: 'print(“hello world”)',
      image: '/winners/2024/2024-6th copy.jpg',
      members: [
        'Andre Camerino',
        'Evan Au',
        'Luase Fontaine',
        'Ashlee Shum',
        'Gabrielle Esguerra',
        'Jayden Newport',
      ],
    },
  ],
};
