# fly.toml app configuration file generated for wdccxsesahackathon-com on 2025-01-23T16:03:18+13:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wdccxsesahackathon-com'
primary_region = 'syd'
swap_size_mb = 512

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
