name: Deploy to GitHub Pages

on:
  push:
    branches:
      - staging  # Automatically deploy on staging branch
  workflow_dispatch: # Allow manual triggering for production

jobs:
  staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build and export for staging
        run: npm run build

      - name: Deploy to Staging
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run staging

  production:
    name: Deploy to Production
    needs: staging # Wait for staging to finish
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' # Only trigger manually

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build and export for production
        run: npm run build

      - name: Deploy to Production
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run deploy
